### ISSUE TITLE
Collection visible in the Roles/Agent Browser ?

### ISSUE THREAD

**Issue by smassonnat** [cristal-ise/gui#11]
When you browse the Role/Agent Tree, the collection aren't shown as it is done for the Item (see below).
![bug_gui_collection_agent](https://cloud.githubusercontent.com/assets/9263650/10221396/734af64e-684e-11e5-9d2c-6e7b55d07d6b.JPG)

Should we keep it this way ?

**Comment by abranson** [comment]
Good idea.
