### ISSUE TITLE
missing Activities in Activity selector (CAD)

### ISSUE THREAD

**Issue by smassonnat** [cristal-ise/gui#15]
When Editing a CAD, the Activity selector doesn't display all the Activities available.
And no error in the log.

![bug_gui_selector_activities](https://cloud.githubusercontent.com/assets/9263650/10540420/06362446-7408-11e5-967d-6e3fd996d07e.jpg)

I tried to figure out if there is some difference between activities not diplayed and those that are visible, but could not find anything...

**Comment by smassonnat** [comment]
We made a little inquiry with Zsolt and found that only the activities I've created are impacted and are not visible from the Activities selector.

I've roll back my GUI project to its previous versions, to see if I encounter the same bug : 
- 187f399 same bug, some of the activities that I've created are not visible
- b999ef5 this one doesn't compile on my side, so I wasn't able to test it
- 7843814  works fine, I'm able to see all the activities.

For now I'm running on the last version that works : 7843814

**Comment by abranson** [comment]
Hi,

The new activity chooser searches for activities in the whole tree, filtering Items by properties. The old one just listed all the Items in /desc/ActivityDesc. Have you defined your own properties for your activities? It looks for Type:ActivityDesc and Complexity:Elementary.

**Comment by smassonnat** [comment]
That's one of the first things that came into my mind, so i've already checked it : all of them have those props.
Here the properties of one of my activity that doesn't appears in the selector.
![bug_gui_selector_activities_2](https://cloud.githubusercontent.com/assets/9263650/10542458/9da89fce-7418-11e5-9352-b2c5efb13e96.jpg)

**Comment by abranson** [comment]
I haven't been able to replicate it yet here. Are there any batch size settings in ApacheDS or anything like that?

Probably a good idea to search directly in ApacheDS if you can. Just for those two cristalprop attributes from the domain root.
