### ISSUE TITLE
Duplicate resources in LifecycleImport.xml

### ISSUE THREAD

**Issue by smassonnat** [cristal-ise/gui#7]
When using the "Export" button on a CompositeActivity, I've got duplicate resources entries in the generated file (see screenshot below).

![bug_export_workflow](https://cloud.githubusercontent.com/assets/9263650/9383248/eb72214c-4747-11e5-9fa0-7eb7cf0b0a97.jpg)

**Comment by abranson** [comment]
Part of the module export functionality described in #8
